### ISSUE TITLE
X-Bc-Customer-Id Header Failing to Retrieve Customer Data

### ISSUE THREAD

**Issue by ccucunubatrellis** [bigcommerce/catalyst#1227]
**Describe the bug**

We noticed that there is no result data for cart and checkout operations after a user logs in on the app and the `X-Bc-Customer-Id` header is passed with the user ID in the requests. According to the documentation, [customer access tokens](https://developer.bigcommerce.com/docs/start/authentication/graphql-storefront#customer-access-tokens) are the recommended approach to access customer data. After we switched to using the customer access tokens, the data returned as expected.

**To Reproduce**

related: https://bigcommerce.my.site.com/s/question/0D54v000099DwT1CAK/adding-item-to-cart-for-customer-but-calling-the-customers-cart-returns-null?language=es_MX

1. Add a product to the cart.
2. Sign in.
3. Go to the cart page and observe that the data is not being returned.

**Comment by bookernath** [comment]
@ccucunubatrellis thank you for the report; this was possible due to the cart not being properly upgraded from guest -> customer cart using the appropriate GQL mutation at the moment of login.

To your point, Customer Access Tokens are now preferred and have many advantages over the previous approach. Once https://github.com/bigcommerce/catalyst/pull/1262 is merged we can close this issue.

**Comment by chanceaclark** [comment]
#1262 is merged so we can close this
