### ISSUE TITLE
Not Found Page (404) is showing nextjs's default error page

### ISSUE THREAD

**Issue by onur-o7** [bigcommerce/catalyst#956]
**Describe the bug**

App does not utilize custom 404 page with header,footer and featured products as intended.

And App also requesting notfound query on homepage. without needing. it overlaps with Layout Query.

[https://catalyst-demo.site/foo-bar/](https://catalyst-demo.site/foo-bar/)

**To Reproduce**
1. Go to a page that is not Found
2. See error

**Expected behavior**

When the route not found app should show 404 page inside the main layout.

**Screenshots**

<img width="1439" alt="Screenshot 2024-05-30 at 17 20 14" src="https://github.com/bigcommerce/catalyst/assets/96867126/8cb93b2a-e1d9-4463-8be5-be5d35ec2806">

<img width="528" alt="Screenshot 2024-05-30 at 17 34 43" src="https://github.com/bigcommerce/catalyst/assets/96867126/7edb7013-0359-4e5b-8c5d-9ad13b43d5ff">

**Comment by deini** [comment]
@onur-o7 Thanks for reporting this! Got fixed in #957 should roll out to our sample stores soon.

> And App also requesting notfound query on homepage. without needing. it overlaps with Layout Query.

This is unfortunately expected behavior with next, you can read more about it in these links:
- https://github.com/vercel/next.js/discussions/55583
- https://github.com/vercel/next.js/blob/e4a831c188ed0639132c55c73ee9ee26ec350063/packages/next/src/server/app-render/create-component-tree.tsx#L278-L282
